### ISSUE TITLE
Android - Make the switch between Visual and HTML Editor working

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/react-native-aztec#11]
Tapping on the toolbar to switch from Visual editor to HTML Editor shows a blank editor.

- We need to make sure the correct height of the HTML editor is properly calculated and set.
- Same thing should happen when switching back to Visual editor.

I've already started working on this, will comment with the link to my branch.

**Comment by daniloercoli** [comment]
@mzorz - I started working on fixing this in the branch `issue/fix-HTML-editor-blank`. Note that a small change to Aztec is also required. This new branch already points to the correct hash.

**Comment by mzorz** [comment]
As discussed elsewhere, we don't really need to switch an individual Aztec component to HTML, but rather the expected experience is to be able to switch Gutenberg itself from visual block editor to a full Post content HTML editor. The HTML toggle should probably live elsewhere maybe as an option menu rather than a toolbar, and affect the whole thing i.e. Gutenberg instead of a specific block.

![gutenberghtml](https://user-images.githubusercontent.com/6597771/39127228-c42cfba8-46da-11e8-9f87-17a1d9af6c58.gif)

Closing this issue as we work towards this form 👍
